- apps/client/src/app/about/page.tsx
- apps/client/src/app/list/[category]/page.tsx
- apps/client/src/components/Header/index.tsx
> header 수정했습니다.
- about 페이지, postlist page 생성
- Header 홈 링크 추가
> [Client] Update header

- apps/admin/src/app/post/write/page.tsx
행사 갤러리 글 첨부파일이 없이 등록시 예외처리를 하였습니다
+ submit버튼에  disabled 속성 추가
> [Admin] Add write Exception handling

- apps/admin/src/app/post/write/page.tsx
- packages/ui/src/components/Button/index.tsx
> 글 작성 로직 수정했습니다.
- useMutation의 isLoading으로 요청에 대한 응답 대기 시, button을 disabled 처리했습니다
> [Admin] Update write logic

- apps/client/src/app/page.tsx
- packages/common/src/styles/theme.ts
> breakpoint 추가
- breakpoint 추가했습니다
> [Common] Add breakpoint

- apps/client/src/components/Title/About/index.tsx
- apps/client/src/components/Title/SubTitle/index.tsx
> [Client] AboutTitle

- apps/client/src/app/page.tsx
- apps/client/src/components/NoticeBanner/Banner/style.ts
- apps/client/src/components/NoticeBanner/index.tsx
- apps/client/src/components/NoticeBanner/style.ts
> NoticeBanner 반응형 추가
> root 경로에서 확인 가능합니다.
+ 디자인에는 학사 일정이 끼워져있어 제외하여 생각하고 제작하였습니다.
> [Client] NoticeBanner Responsive

- apps/client/src/components/PostContent/index.stories.tsx
- apps/client/src/components/PostContent/index.tsx
- apps/client/src/components/PostContent/style.ts
> PostContent 컴포넌트를 제작하였습니다.
아래 사진에 해당하는 컴포넌트입니다.
postSeq를 prop으로 받아서 data를 가져옵니다.
+ storybook에서 postSeq 174,5,6으로 여러 이미지 확인 가능합니다.
+ postSeq 143,144로 사진 파일 예외처리 확인 가능합니다.
> [Client] postContent 

- apps/client/src/components/CategoryHeader/index.tsx
- apps/client/src/components/CategoryHeader/style.ts
- apps/client/src/components/GalleryCard/style.ts
- apps/client/src/components/MainPage/GalleryList/index.tsx
- apps/client/src/components/MainPage/GalleryList/style.ts
> GalleryListPreview
아래 사진과 같이 동작합니다.
+ default
+ 1440
+ 1024
+ 600
> [Client] GalleryListPreview Responsive

- apps/client/src/components/CategoryHeader/style.ts
- apps/client/src/components/MainPage/NewsletterList/index.tsx
- apps/client/src/components/MainPage/NewsletterList/style.ts
- apps/client/src/components/NewsletterCard/style.ts
- packages/api/client/src/hooks/index.ts
> 가정통신문의 반응형을 제작하였습니다.
+ 아래 사진과 같이 동작합니다.
> [Client] NewsLetter Responsive

- apps/client/src/assets/svg/FooterGSMLogo.tsx
- apps/client/src/components/Footer/index.tsx
- apps/client/src/components/Footer/style.ts
> Footer 반응형 추가
- Footer 반응형 추가
- FooterGSMLogo isSmall prop 추가
아래에서 확인 가능합니다.
https://official-gsm-client-git-feature-clientfooter-the-moment.vercel.app/
> [Client] Footer Responsive

- apps/client/src/assets/index.ts
- apps/client/src/assets/svg/icon/HamburgerIcon.tsx
- apps/client/src/components/Header/index.tsx
- apps/client/src/components/Header/style.ts
> header 반응형 추가했습니다.
- home의 main content와 일관된 width를 유지하도록 하였습니다
hamburger menu 제작
> [Client] Header responsive

- apps/client/src/app/about/6/page.tsx
- apps/client/src/components/About/Section6/BusinessCard/index.tsx
- apps/client/src/components/About/Section6/BusinessCard/style.ts
- apps/client/src/components/About/Section6/index.tsx
- apps/client/src/components/About/Section6/style.ts
- apps/client/src/types/about/business.ts
> section6 반응형 작업을 하였습니다.
자세한 사항은 https://official-gsm-client-git-feature-section6-the-moment.vercel.app/about/6 에서 확인 가능합니다.
- 1920 ~ 1024
- 1024 ~ 600
> [Client] Section6 responsive

- apps/client/src/components/About/Section1/CircleDecoration/style.ts
- apps/client/src/components/About/Section1/Title/style.ts
- apps/client/src/components/About/Section1/index.tsx
Section1 반응형
Section1은 브라우저 width가 600일때만 스타일이 변경됩니다.
+ 600
+ CircleDecoration컴포넌트 수정
+ Section1내 Title 컴포넌트 수정
> [Client] Section1 responsive

- apps/client/src/components/About/Section7/style.ts
> section7 반응형 작업
- breakpoint[600]
- breakpoint[1024]
> [Client] section7 responsive

- apps/client/src/components/MainPage/NewsletterList/style.ts
- apps/client/src/components/NewsletterCard/index.tsx
- apps/client/src/components/NewsletterCard/style.ts
- apps/client/src/components/NoticeBanner/Banner/index.tsx
- apps/client/src/components/NoticeBanner/Banner/style.ts
> home page의 링크 연결이 되지 않은 곳에 링크를 추가했습니다
div -> Link
- NoticeBanner
- NewsletterCard
- NewsletterList
> [Client] add Link in home

- apps/client/src/app/about/5/page.tsx
- apps/client/src/components/About/Section5/index.tsx
- apps/client/src/components/About/Section5/sectionHeight.ts
- apps/client/src/components/About/Section5/style.ts
> section5 영역에서 스크롤 할 때 과 선택이 바뀌게 개선했습니다.
- majorScroll ref 추가
- 과 선택 영역 범위: 2600 - 1100 = 1500
- 0  ~ 500 -> 'SW'
- 500 ~ 1000 -> 'IOT'
- 1000 ~ 1500 -> 'AI' 
https://official-gsm-client-git-feature-section5-the-moment.vercel.app/about 해당 페이지에서 확인 가능합니다.
- hover style 추가
> [Client] Scoll Section5

- apps/client/src/app/page.tsx
- apps/client/src/components/PromotionVideo/style.ts
- PromotionVideo 반응형 디자인 추가
- width < 1024 부터 video height가 43.75rem (700px)로 고정됩니다.
width < 1024
width < 600
https://official-gsm-client-git-feature-clientpromotionvideo-the-moment.vercel.app/
위에서 확인 가능합니다
> [Client] PromotionVideo responsive

- apps/client/src/components/NoticeBanner/index.tsx
- apps/client/src/components/NoticeBanner/style.ts
> NoticeBanner의 슬라이드 간격을 수정하였습니다.
> 동작 영상입니다.
현재 슬라이드 속도는 5초, 간격은 30vw입니다.
https://github.com/themoment-team/official-gsm-front/assets/106712562/8fb13075-1c5b-42d1-a758-85da275a30e8
> [Client] Update NoticeBanner Slide Gap

- apps/client/src/app/post/[postSeq]/page.tsx
- apps/client/src/components/PostPage/AssembledPost/style.ts
- apps/client/src/components/PostPage/PostContent/style.ts
- apps/client/src/components/PostPage/PostDetailHead/style.ts
- packages/ui/src/components/FileButton/style.ts
> PostDetilPage에 반응형을 추가하였습니다.
아래 사진과 같이 동작합니다.
+ default
+ 1024
+ 600
> [Client] PostDetilPage Responsive

- apps/client/src/assets/index.ts
- apps/client/src/assets/svg/icon/HomeScrollDownIcon.tsx
- apps/client/src/components/About/Section1/index.tsx
- apps/client/src/components/PromotionVideo/index.tsx
- apps/client/src/components/PromotionVideo/style.ts
- apps/client/src/components/Scroll/index.stories.tsx
- apps/client/src/components/Scroll/index.tsx
- apps/client/src/components/Scroll/style.ts
- apps/client/src/components/index.ts
> 스크롤 유도 아이콘을 추가 했습니다
https://github.com/themoment-team/official-gsm-front/assets/80103328/48c3c78b-68b0-4531-9d60-4337706335e9
https://official-gsm-client-git-feature-promotionvideo-the-moment.vercel.app/
> [Client] Add scroll feedback in PromotionVideo

- apps/client/src/components/About/Section4/CurriculumCards/index.tsx
- apps/client/src/components/MainPage/Header/index.tsx
lint error를 해결하였습니다
48d6858 여기서 확인가능합니다!
> [Client] Resolve lint error

- apps/admin/next.config.js
- apps/client/next.config.js
admin next.config에 images domain을 변경하였습니다.
643d226 여기서 확인 가능합니다.
> [Admin] edit next config

- apps/client/src/app/layout.tsx
- apps/client/src/app/page.tsx
- apps/client/src/components/About/Section4/CurriculumCards/index.tsx
- apps/client/src/components/MainPage/Header/index.tsx
- apps/client/src/components/index.ts
- apps/client/src/components/navigation-events.ts
- apps/client/src/lib/gtag.ts
> PageView를 추적할 수 있도록 하였습니다.
+ navigation-events를 생성하였습니다.
+ Layout에 navigation-events를 위치시켰습니다.
> [Client] Page View

- apps/admin/src/components/ApproveModal/ApproveItem/style.ts
- apps/admin/src/components/ApproveModal/style.ts
- apps/admin/src/components/AuthError/style.ts
- apps/admin/src/components/AuthTitle/style.ts
- apps/admin/src/components/Carousel/Controller/style.ts
- apps/admin/src/components/Carousel/style.ts
- apps/admin/src/components/Category/style.ts
- apps/admin/src/components/CommonDetail/style.ts
- apps/admin/src/components/DeleteModal/style.ts
- apps/admin/src/components/DeletePostButton/style.ts
- apps/admin/src/components/FileCard/style.ts
- apps/admin/src/components/FileUploadLabel/style.ts
- apps/admin/src/components/FormCategory/style.ts
> Admin에서 theme를 적용하였습니다.
> A~F로 시작하는 컴포넌트들에 theme를 적용하였습니다.
ApproveModal부터 FormCategory까지 작업되었습니다.
> [Admin] Update admin theme (A~F) |  Low Priority

- apps/admin/src/components/ApproveModal/ApproveItem/style.ts
- apps/admin/src/components/ApproveModal/style.ts
- apps/admin/src/components/AuthError/style.ts
- apps/admin/src/components/AuthTitle/style.ts
- apps/admin/src/components/Carousel/Controller/style.ts
- apps/admin/src/components/Carousel/style.ts
- apps/admin/src/components/Category/style.ts
- apps/admin/src/components/CommonDetail/style.ts
- apps/admin/src/components/DeleteModal/style.ts
- apps/admin/src/components/DeletePostButton/style.ts
- apps/admin/src/components/FileCard/style.ts
- apps/admin/src/components/FileUploadLabel/style.ts
- apps/admin/src/components/FormCategory/style.ts
- apps/admin/src/components/GalleryCard/style.ts
- apps/admin/src/components/GoogleLoginButton/style.ts
- apps/admin/src/components/Header/style.ts
- apps/admin/src/components/Input/style.ts
- apps/admin/src/components/LogoutModal/style.ts
- apps/admin/src/components/PostButton/style.ts
- apps/admin/src/components/PostCard/style.ts
- apps/admin/src/components/PostListHeader/style.ts
- apps/admin/src/components/TextArea/style.ts
> Admin에서 theme를 적용하였습니다.
> G~T로 시작하는 컴포넌트들에 theme를 적용하였습니다.
GalleryCard부터 ToBackButton까지 작업되었습니다.
> [Admin] Update admin theme (G~T) | Low Priority 

- apps/admin/src/components/Category/index.stories.tsx
- apps/client/src/components/Header/index.stories.tsx
- apps/storybook/.storybook/main.ts
- pnpm-lock.yaml
> 빌드 시, 의존성을 찾지 못하여 발생한 에러를 해결했습니다.
- 의존성들 재 설치 
- storybook package의 .storybook/main.ts의 babel에 importSource 옵션 추가
> [*] Fix build error

- apps/admin/src/components/ApproveModal/index.tsx
- apps/admin/src/components/ApproveModal/style.ts
- apps/admin/src/components/DeleteModal/index.tsx
- apps/admin/src/components/DeleteModal/style.ts
- apps/client/src/components/MainPage/GalleryList/index.stories.tsx
- packages/common/src/utils/filterImages.ts
Fix minor typos
- Conatiner -> Container
- Cancle -> Cancel
- extentions -> extensions
- Gallary -> Gallery
> Fix minor typos

- apps/client/src/components/Footer/index.tsx
footer 관리자 링크를 추가하였습니다.
48777a7 에서 확인 가능합니다.
> [Client] add footer link

- README.md
> README에 skill set을 추가 했습니다.
https://github.com/themoment-team/HiRecruit-front/blob/master/README.md
위 HiRecruit의 README skill set의 template을 사용했습니다
> [*] Update README

- apps/client/src/components/About/Location/Map/index.tsx
- apps/client/src/components/About/Location/index.tsx
- apps/client/src/components/About/Location/style.ts
> 찾아오는길 반응형
**- breakpoint[1024]**
**- breakpoint[600]**
> [Client] 찾아오는길 반응형

- packages/ui/src/components/PaginationController/index.tsx
오타를 수정하였습니다
9455980 여기서 확인가능합니다.
> Update fix typo error

- apps/client/src/components/PopUpCard/index.stories.tsx
- apps/client/src/components/PopUpCard/index.tsx
- apps/client/src/components/PopUpCard/style.ts
- apps/client/src/components/index.ts
팝업 카드를 제작했습니다.
- 팝업 카드를 제작했습니다.
storybook, client/PopUpCard에서 확인 가능하십니다.
PopUpCardProps의 내용들은 추후 API 명세서가 업데이트됨에 따라 수정하겠습니다.
> [Client] Add popUpCard
